perl-dev/Docker: make for smaller dockers. It's a slower build though and the fetch isn't multilayered
- clean up yum cache
- clean up perl/cpan in the same RUN
- all cpan builds in the same RUN
- an extra FROM scratch to squash the layers into 1 and clear
  intermediate empty ones

diff --git a/dockers/perl-dev/Dockerfile b/dockers/perl-dev/Dockerfile
--- a/dockers/perl-dev/Dockerfile
+++ b/dockers/perl-dev/Dockerfile
@@ -6,29 +6,28 @@ ARG perl_version=5.32.0
 # we start from Amazon Linux 2 with sources to build perl against, we also add
 # busybox. We do a COPY to "start fresh", just because we can't (yet?) overlay
 # multiple FROM dockers into 1 docker sadly enough
-FROM amazonlinux:2-with-sources as base-image
 FROM busybox:1.32.0             as busybox
-FROM scratch
+FROM amazonlinux:2-with-sources as base-image
+# start from scratch (nr.1)
+FROM scratch                    as perl-dev-build
 COPY --from=base-image / /
 COPY --from=busybox    /bin/busybox /
 
 ENV perl_version=${perl_version:-5.32.0}
-RUN echo Building for PERL ${perl_version}
-RUN echo DOCKER_TAG: ${DOCKER_TAG}
+RUN echo Building for PERL ${perl_version}; echo DOCKER_TAG: ${DOCKER_TAG}
 
 MAINTAINER Tim Aerts <aardbeiplantje@gmail.com>
 
-# base build stuff
-RUN yum install -y make gcc tar gzip pkgconfig man groff
-
 # needed for building PERL and possibly cpan stuff (note that they are not
-# included in the end perl-sandbox as they don't go in /opt)
+# included in the end perl docker as they don't go in /opt)
 RUN yum install -y   \
         gdbm-devel   \
         libdb-devel  \
         gcc          \
         make         \
         tar          \
+        man          \
+        groff        \
         curl         \
         xz           \
         gzip         \
@@ -41,10 +40,10 @@ RUN yum install -y   \
         ncurses-libs \
         coreutils    \
         findutils    \
-        patch
-
-# to be sure to have that
-ENV LD_LIBRARY_PATH=/opt/lib64:/opt/lib:/opt/lib/perl5/${perl_version}/x86_64/CORE
+        patch;       \
+    yum clean all;   \
+    rm -rf /var/lib/yum/repos; \
+    exit 0
 
 # now we add OS dependencies from / to /opt, as later on we will be squashing
 # the docker fs by moving everything from /opt to / and abandon what's there
@@ -64,36 +63,22 @@ RUN    mkdir -p                             /opt/lib64/ \
     && cp -a /usr/lib64/libc-*.so*          /opt/lib64/ \
     && cp -a /usr/lib64/libnsl.so*          /opt/lib64/ \
     && cp -a /usr/lib64/libnsl-*.so*        /opt/lib64/ \
-    && (cd /opt && ln -s / usr) \
-    && (cd /opt && ln -s / opt)
-
-# fix a few symlinks
-RUN    rm /opt/lib64/libcrypt.so         && (cd /opt/lib64 && ln -s libcrypt.so.1     libcrypt.so)   \
+    && (cd /opt && ln -s / usr)                         \
+    && (cd /opt && ln -s / opt)                         \
+    && rm /opt/lib64/libcrypt.so         && (cd /opt/lib64 && ln -s libcrypt.so.1     libcrypt.so)   \
     && rm /opt/lib64/libdl.so            && (cd /opt/lib64 && ln -s libdl.so.2        libdl.so)      \
     && rm /opt/lib64/libnsl.so           && (cd /opt/lib64 && ln -s libnsl.so.1       libnsl.so)     \
     && rm /opt/lib64/libutil.so          && (cd /opt/lib64 && ln -s libutil.so.1      libutil.so)    \
     && rm /opt/lib64/libc.so             && (cd /opt/lib64 && ln -s libc.so.6         libc.so)       \
     && rm /opt/lib64/libm.so             && (cd /opt/lib64 && ln -s libm.so.6         libm.so)       \
-    && rm /opt/lib64/libpthread.so       && (cd /opt/lib64 && ln -s libpthread.so.0   libpthread.so)
-
-# PERL CORE modules need extra libs from the OS
-RUN    \
-       cp -a /usr/lib64/libgdbm*            /opt/lib64/ \
+    && rm /opt/lib64/libpthread.so       && (cd /opt/lib64 && ln -s libpthread.so.0   libpthread.so) \
+    && cp -a /usr/lib64/libgdbm*            /opt/lib64/ \
     && cp -a /usr/lib64/libdb.so*           /opt/lib64/ \
     && cp -a /usr/lib64/libdb-*.so*         /opt/lib64/
 
-# copy a real bash temporarily: before busybox --install -s as that add 'sh'
-RUN mkdir -p /opt/bin                            \
-    && cp /bin/bash  /opt/bin/bash               \
-    && (cd /opt/bin && ln -s ./bash sh)          \
-    && cp /lib64/libtinfo.so*  /opt/lib64/       \
-    && (cd /opt/lib64 && ln -s libtinfo.so.5 libtinfo.so)
-
-# setup a /tmp for File::Temp
-RUN mkdir /opt/tmp && chmod 1777 /opt/tmp
-
 # for easy script adding, this is also added to the PATH
-RUN mkdir /opt/scripts
+# setup a /tmp for File::Temp
+RUN mkdir /opt/scripts; mkdir /opt/tmp && chmod 1777 /opt/tmp
 
 # copy busybox for debugging, add at least 'sh' for docker builds later on if
 # we move from /opt to /. busybox can later on also be used in the perl-docker
@@ -102,18 +87,30 @@ RUN    mkdir -p /opt/lib64                   \
     && cp /busybox /opt/bin/busybox          \
     && (cd /opt/bin && for m in $(/opt/bin/busybox --list); do ln -s ./busybox $m; done)
 
-ENV PATH=/opt/bin:$PATH
-
 # make sure to move /bin/sh away and start Configure with /opt/bin/sh which is
 # at this point a full sh -> bash.  This is for later on, when perl in /opt
 # needs to use sh for `` and system() calls, the default needs to be
 # /opt/bin/sh as /bin/sh will simply not be there.
+#
+# Immediately install and cleanup the src directory so the docker layer stays
+# "small"
+#
+# copy a real bash temporarily: before busybox --install -s as that add 'sh'
+# after the perl build, switch the fat bash back to busybox sh
+
+ENV LD_LIBRARY_PATH=/opt/lib64:/opt/lib:/opt/lib/perl5/${perl_version}/x86_64/CORE
+ENV PATH=/opt/bin:$PATH
 
 WORKDIR /opt/src/perl
 RUN \
-       export perl_tar=perl-${perl_version}.tar.xz;                                            \
-       echo   P:$perl_tar;                                                                   \
-       curl -sSL -k --insecure https://www.cpan.org/src/5.0/$perl_tar -o $perl_tar           \
+       mkdir -p /opt/bin                                                                     \
+    && cp /bin/bash  /opt/bin/bash                                                           \
+    && (cd /opt/bin && rm sh && ln -s ./bash sh)                                             \
+    && cp /lib64/libtinfo.so*  /opt/lib64/                                                   \
+    && (cd /opt/lib64 && ln -s libtinfo.so.5 libtinfo.so)                                    \
+    ;  export perl_tar=perl-${perl_version}.tar.xz                                           \
+    ;  echo   P:$perl_tar                                                                    \
+    ;  curl -sSL -k --insecure https://www.cpan.org/src/5.0/$perl_tar -o $perl_tar           \
     && echo '6f436b447cf56d22464f980fac1916e707a040e96d52172984c5d184c09b859b *'${perl_tar}  \
         |sha256sum -c -                                                                      \
     && tar --strip-components=1 -xaf $perl_tar -C /opt/src/perl                              \
@@ -134,13 +131,20 @@ RUN \
         -des                                                                                 \
     && make -j16                                                                             \
     && make -j16 install                                                                     \
-    && rm -rf /opt/src/perl                                                                  \
-    && mv /bin/sh.b /bin/sh
+    && rm -rf /opt/src/perl/*                                                                \
+    && mv /bin/sh.b /bin/sh                                                                  \
+    ; (cd /opt/bin && rm bash sh && ln -s busybox sh) && rm /opt/lib64/libtinfo*             \
+    ; rm -rf /opt/src/perl                                                                   \
+    ; rm -rf /opt/tmp/cpan                                                                   \
+    ; rm -rf /opt/src                                                                        \
+    ; rm -rf /opt/share                                                                      \
+    ; rm -rf /opt/man                                                                        \
+    ; rm -rf /opt/include                                                                    \
+    ; rm -rf /opt/games                                                                      \
+    ; rm -rf /opt/perl                                                                       \
+    ; rm -rf /opt/lib/python*
 
 WORKDIR /
-
-# after the perl build, switch the fat bash back to busybox sh
-RUN (cd /opt/bin && rm bash sh && ln -s busybox sh) && rm /opt/lib64/libtinfo*
 
 ENV INSTALL_BASE=/tmp/cpan/local
 ENV LD_LIBRARY_PATH=/opt/lib64:/opt/lib:/opt/lib/perl5/${perl_version}/x86_64/CORE
@@ -172,39 +176,57 @@ COPY cpan_config.pl /tmp/
 # in the end docker, we can't do anything with those and they take up space.
 # Best is to look out for those while installing cpan modules that are needed,
 # often they bring in dependencies that aren't needed later on at runtime
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  CPAN
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  YAML
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  ExtUtils::PkgConfig
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  ExtUtils::Helpers
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  HTTP::Date
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  HTML::Tiny
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  install
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Canary::Stability
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Algorithm::Diff
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Spiffy
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Text::Diff
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Base
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Deep
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::LeakTrace
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  inc::latest
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Module::Build
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  common::sense
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::More
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Simple
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Builder
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Harness
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test2
-RUN /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test2::Formatter
+RUN \
+       /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  CPAN                  \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  YAML                  \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  ExtUtils::PkgConfig   \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  ExtUtils::Helpers     \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  HTTP::Date            \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  HTML::Tiny            \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  install               \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Canary::Stability     \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Algorithm::Diff       \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Spiffy                \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Text::Diff            \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Base            \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Deep            \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::LeakTrace       \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  inc::latest           \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Module::Build         \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  common::sense         \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::More            \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Simple          \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Builder         \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test::Harness         \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test2                 \
+    && /opt/bin/perl /opt/bin/cpan -j /tmp/cpan_config.pl -Ti  Test2::Formatter      \
+    || exit 1                                                                        \
+    ; rm -rf /opt/tmp/cpan                                                           \
+    ; rm -rf /opt/src                                                                \
+    ; rm -rf /opt/share                                                              \
+    ; rm -rf /opt/man                                                                \
+    ; rm -rf /opt/include                                                            \
+    ; rm -rf /opt/games                                                              \
+    ; rm -rf /opt/perl                                                               \
+    ; rm -rf /opt/lib/python*                                                        \
+    ; find /opt/lib/perl5/ -type f -name '.packlist'|xargs rm -f                     \
+    ; mkdir -p /opt/tmp && chmod 1777 /opt/tmp
 
-# cleanup stuff in /opt we never will need
-RUN    rm -rf /opt/src                \
-    && rm -rf /opt/share              \
-    && rm -rf /opt/man                \
-    && rm -rf /opt/include            \
-    && rm -rf /opt/games              \
-    && rm -rf /opt/perl               \
-    && rm -rf /opt/lib/python*        \
-    && mkdir -p /opt/tmp && chmod 1777 /opt/tmp
+# for testing, add the core modules test script
+COPY test_core_modules.pl /tmp/
+
+# and test this, if it fails, the docker image isn't tagged
+RUN /opt/bin/perl /tmp/test_core_modules.pl
+
+# start from scratch (nr.2)
+FROM scratch
+COPY --from=perl-dev-build / /
+
+# reset ENV variables we don't need anymore
+ENV PERL5LIB=
+ENV TMPDIR=
+ENV LD_LIBRARY_PATH=
+ENV PATH=/opt/bin/:/opt:$PATH
 
 # reset the default cpan install, this way, new cpan modules go to site_perl
 ENV INSTALL_BASE=
@@ -222,21 +244,4 @@ ENV INSTALL_BASE=
 # E.g.:
 # RUN /opt/bin/cpan -j /tmp/cpan_config.pl -Ti JSON::XS
 #
-
-
-# after the extra cpan modules install, cleanup the .h files
-RUN find /opt/lib/perl5/ -type f -name '.packlist'|xargs rm
-
-# reset other ENV variables we don't need anymore
-ENV PERL5LIB=
-ENV TMPDIR=
-ENV LD_LIBRARY_PATH=
-
-# for testing, add the core modules test script
-COPY test_core_modules.pl /tmp/
-
-# and test this, if it fails, the docker image isn't tagged
-RUN /opt/bin/perl /tmp/test_core_modules.pl
-
-ENV PATH=/opt/bin/:/opt:$PATH
 ENTRYPOINT ["/opt/bin/busybox", "sh"]
